name = "download-and-analysis-player-information"
main = "src/index.js"
compatibility_date = "2024-12-11"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Uncomment to enable environment-specific deployments
# [env.production]
# name = "download-and-analysis-player-information-production"
# 
# [env.staging]
# name = "download-and-analysis-player-information-staging"

